### ISSUE TITLE
3.8.1 roadmap

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7687]
Hello there,

There are growing discussions about the future of MonoGame, which the admins are well aware and I'd like to dispel one thing: MonoGame is alive. We'll come back to this at when 3.8.1 will be released with a roadmap for 3.9 and beyond, as well as a post explaining what has been going on behind the scene and how you can help by contributing to MonoGame.

For the time being, here is the short term plan for releasing a 3.8.1 version to get things rolling.
The goal of 3.8.1 is to make MonoGame .NET 6 and VS 2022 ready. Other issues will be addressed separately for 3.9 or an intermediate 3.8.x release.

------------

Switch relevant projects to ```net6``` ```TargetFramework``` (```dotnet cake``` must pass on NET 6):
- [x] MonoGame.Framework.Android
- [x] MonoGame.Framework.iOS
- [x] MonoGame.Framework.WindowsDX (This one also has a ```net452``` target which we should keep for the time being because it is used a reference for consoles)
- [x] MonoGame.Framework.WindowsUniversal
- [x] MonoGame.Framework.DesktopGL (It uses ```netstandard2.0``` which is cool to keep a VS2019 compatibility, so no need to update it. It also has a ```net452``` target for console reference)
- [x] Make a "console" target to build against ```452``` so that we have safe checks on github actions to make sure that the console repositories are still compatible with the main repository (duplicating DesktopGL should do the trick) #7698
- [x]  MonoGame.Framework.Content.Pipeline (It uses ```netstandard2.0``` which is cool to keep a VS2019 compatibility, so no need to update it)
- [x] MonoGame.Content.Builder
- [x] MonoGame.Effect.Compiler
- [x] MonoGame.Content.Builder.Task
- [x] MonoGame.Packaging.Flatpak (It uses ```netstandard2.0``` which is cool to keep a VS2019 compatibility, so no need to update it. It also has a ```net46``` target but I don't know why, maybe @harry-cpp knows?)
- [x] MonoGame.Tools.Tests
- [x] MonoGame.Builder.Editor.Linux #7708
- [x] MonoGame.Builder.Editor.Mac #7708
- [x] MonoGame.Builder.Editor.Windows #7708
- [x] MonoGame.Content.Builder.Editor.Launcher #7708
- [x] MonoGame.Tests.DesktopGL
- [x] MonoGame.Tests.WindowsDX
- [x] Update mgfxc_wine_setup.sh to download and install net6 on wine #7790

Updating templates for ```net6``` (compilation and run must be tested):
- [x] MonoGame.Application.Android.CSharp (this one might need to be converted to the newer SDK-Style csproj format)
- [x] MonoGame.Application.DesktopGL.CSharp
- [x] MonoGame.Application.iOS.CSharp (this one might need to be converted to the newer SDK-Style csproj format)
- [x] MonoGame.Application.UWP.CoreApp.CSharp (this one might just need an UAP version bump)
- [x] MonoGame.Application.UWP.XAML.CSharp (this one might just need an UAP version bump)
- [x] MonoGame.Application.WindowsDX.CSharp
- [x] Populate MGCB version in the tool config file of the templates at build time (like the in the csproj)
- [x] Test mobile and UWP templates #7697

VS Extension:
- [x] [Make a Visual Studio Extension](https://github.com/sayedihashimi/template-sample#how-to-ship-a-template-inside-of-a-visual-studio-extension-vsix) to have the templates on the VS 2022 marketplace #7699
- [x] Have the VS extension to configure .mgcb files to be open with the MGCB editor #7765
- [x] Upgrade VS for Mac extension to support VS for Mac 2022
- [x] Figure out a way to do a ```dotnet tool restore``` if the MGCB Editor hasn't been restored
- [x] Automate VS for Windows extension versioning #7788

Documentation:
- [x] Reflect on the fact that .NET 6 requires VS2022, which will apply to Android, iOS, WindowsDX, and WindowsUniversal #7798

Optional but very welcome:
- [x] Update SDL2 to its latest version (Windows: with static linking to the VC runtime; macOS: x64+ARM binaries with back-compat to older macOS) #7690 https://github.com/MonoGame/MonoGame.Dependencies/pull/156
- [x] #7701
- [x] #7702

------------

If you wish to contribute, here are a few guidelines:
- make sure to have only NET 6 installed (residual installations of older/newer SDK might hide missing upgrades)
- please test both compilation and running templates before submitting
- mobile targets and WindowsUniversal might need more than just changing the target framework, there are some code changes to expect (they may not be good "first time contributing" tasks, but I don't think this to be difficult, just some gymnastic to expect)
- to build MonoGame, use the ```dotnet cake``` command. This will launch the ```build.cake``` script which builds everything. The objective is to have this script to successfully build

**Comment by mrhelmut** [comment]
Awesome!

I see that we still requires dotnet core 3.1 to build, is there a specific case?

We should be fine upgrading DesktopGL to net6, but it would be nice to keep a net452 target for console reference (though I would also be favorable to remove the net452/net46 targets everywhere and have a separate csproj for console reference).

I would also be okay to merging it, start checking stuff, and fixing as we go.

**Comment by harry-cpp** [comment]
> I see that we still requires dotnet core 3.1 to build, is there a specific case?

iirc, one of the dotnet tools we use during the build process (probably vstemplate) is built against it specifically. Everything on our side is moved to .net 6.0.

**Comment by mrhelmut** [comment]
Alright! So it's just about building the templates and not relevant to building and running MG+ContentBuilder, that sounds perfect.

**Comment by harry-cpp** [comment]
Once I'm home I'll look into opening a PR for it.

**Comment by damian-666** [comment]
I maybe used the wrong template to start but I need the older .net istalled
after vs 2022 plus c#  to build content itself with an existing sln. .
Every build that includes monogame content reference  file  needs it or
gives an error  and niuget doesn't fetch it the dotnet .. prolly just a
project files variable but syntax and formatting is vert very  nuanced. The
error message is crytic so u have to Google to find know this trick to
onboard someone with vs 2022 then tell them to instalm the older dotnet. ..
..if it's a template fix I guess I would use the new template then diff the
projects files or something to fix mine I guess but old sln and project
might fail.. when updating to vs 2022

**Comment by mrhelmut** [comment]
You can't use the templates as-is since the templates alone are not sufficient to make a project net6 compatible. It requires to have both the content builder and the monogame library nugets to be published or self-hosted locally with a NuGet.Config file.

**Comment by SimonDarksideJ** [comment]
There are several docs PR's waiting in the wings @mrhelmut , we should review and also close any other docs gaps that we have queries/issues related to for 3.8.1

**Comment by evilkomododragon** [comment]
It could also be usefull to make a page on the website where people can contribute tutorials and example projects.
Currently nothing on the website itself.

**Comment by mrhelmut** [comment]
Most of the work on the projects has been made and merged by Harry!

We have a working net6 setup. I'll try to spend some time on tasks over the coming days.

**Comment by harry-cpp** [comment]
> MonoGame.Packaging.Flatpak (It uses netstandard2.0 which is cool to keep a VS2019 compatibility, so no need to update it. It also has a net46 target but I don't know why, maybe @harry-cpp knows?)

The project is just a task for msbuild for Linux to package the game into a .flatpak (which is a self contained sanboxed package for Linux). While I was making it, I believe `msbuild` couldn't use netstandard2.0, while `dotnet build` couldn't use net46 so I had to target multiple frameworks to compile it. Updating this project target framework is completely dependant on what `msbuild` and `dotnet build` are compiled against.

**Comment by evilkomododragon** [comment]
I have 2 questions about the future of monogame:

- why was chosen to use .NET of Microsoft and not Mono https://www.mono-project.com/ ?

- will monogame future releases just be bug fixes and .NET updates OR will there be added new features, classes, content pipeline importers, ... to add new functionality to monogame?


thx for reading

**Comment by mrhelmut** [comment]
> why was chosen to use .NET of Microsoft and not Mono https://www.mono-project.com/ ?

Mono _is_ part of .NET runtime and toolchain. Depending on which target you're targeting, .NET will either use Mono or the main CLR.

> will monogame future releases just be bug fixes and .NET updates OR will there be added new features, classes, content pipeline importers, ... to add new functionality to monogame?

There will be an LTS branch with the purpose of keeping an API-compatibility toward XNA, and newer versions which will introduce breaking changes. Just don't expect features which aren't in the scope of MonoGame like a physics engine or an editor.

> Is it correct the content pipeline will be removed?

This is not correct.

**Comment by mrhelmut** [comment]
I've updated the [3.8.1 milestone](https://github.com/MonoGame/MonoGame/milestone/19) and the OP.

Most of the work is done or being worked on. Some documentation tasks are still up for grab if anyone feels like it.

**Comment by evilkomododragon** [comment]
Hi

I would be very interested in a schematic overview of all subprojects listed above and their supported targets.
Also an indication where mono or the main CLR is used.

Maybe somebody is interested to make this so it can be updated each time on a new release to see where targets have changed or added. Also it could be used as a check if all targets are present and all subprojects pass the test for all the assigned (wanted) targets.

Finally it could also give a nice overview to beginners.

**Comment by mrhelmut** [comment]
All of MonoGame's public targets are .NET 6 and follows the .NET 6 guidelines. There is nothing that MonoGame does that will enforce a runtime or form-factor upon you.

.NET 6 is now a unified experience and aims at making things transparent to you in regard to which runtime it will use depending on the scenario. Conceptually speaking, there is no more such things as "dotnet vs mono", they are all part of the same environment and each has its own specialization. So beside saying that MonoGame targets .NET 6, the best we can do is to redirect you to [.NET form-factor documentation](https://github.com/dotnet/designs/blob/main/accepted/2020/form-factors.md) and [deployment models](https://docs.microsoft.com/en-us/dotnet/core/deploying/) for you to choose what's best for your own project.

[The documentation has a suggested path](https://docs.monogame.net/articles/packaging_games.html), but in the end it's up to you.
I'll expand a bit this documentation in preparation for .NET 7 which will add the NativeAOT runtime option that is especially interesting to games.

Consoles are a different kind of beast and rely on an internal tech which is not public, but at some point we'll be looking into unify it as well.

**Comment by evilkomododragon** [comment]
How exactly does the team work on the console implementations (if I can ask)?

- are they stored in a repo not publicly visable?

- are the details on how to program the console's hardware received from the manufacturer (for professionals having a license)?

- are the console implementations made by a special language (assembly?) because I don't think they run C# code directly?

If possible, write something about consoles too (in general, not the things which can't be made public).

**Comment by mrhelmut** [comment]
Will do. I've been intending to write a landfall page for console development and explaining what can be publicly shared and why other things can't.

To answer your questions here:
- everything that is console is private, on separate private repositories
- the manufacturers indeed provide documentation to their own hardware, and we provide the MonoGame documentation and support to licensees
- the console implementations are designed as extensions to this public repositories and are using the same code. The difference being that instead of using OpenGL, SDL, etc., they use custom native C++ libraries that implement the hardware. C# indeed doesn't run on consoles, so the MonoGame team developed its own .NET runtime which takes the compiled IL code to convert it to C++. It's kind of the same process as Unity's own IL2CPP or .NET's NativeAOT.

**Comment by Mindfulplays** [comment]
> I've got everything mostly done for .net 6.0 on my fork: https://github.com/harry-cpp/MonoGame/tree/feature/net6.0 , I was just waiting for VS for Mac 2022 to be released for the finishing touches.

I have migrated to .net6.0 on Windows and am able to build with VS2022.
On Mac, I am able to update `dotnet` (.NET6) alone and still use VS2019 on Mac. /* Aside: There is/was some funkiness if you use the x64/ARM binaries of .NET installer on Mac (early on) but I believe the .NET team has since resolved it. Just need to use the right installer. */

The only weird thing is some .NET6'y thing like `namespace x;` (instead of `namespace x {...}`) doesn't _quite_ work yet (or may be it now does, haven't checked in a while). But all the other stuff (things like records, pattern matching etc) _just work_.

**Comment by mrhelmut** [comment]
For now, MGCB will still have issue on mac M1 + .NET ARM because there are native dependencies which aren't ARM binaries (freetype, assimp, nvtt...). So when trying to build MGCB projects with the ARM variant of .NET 6 on macOS, it will likely fail.
The workaround is to work with the x64 .NET 6 (which can be used to create both ARM and x86 games).

As a priority, we are trying to make compiled games targeting ```osx-arm``` to work natively. That needs building SDL (done) and OpenAL-Soft with ARM support.

MGCB is another story and will likely still require .NET x64 on macOS. The problem is that some of the libraries it depends on might be complex to retrieve and build for ARM.

**Comment by hellphreak** [comment]
Does this mean raspberry pi ARM is also not working for the same reason?

**Comment by mrhelmut** [comment]
No, Raspberry PI works but it is not a platform that MonoGame officially supports. So you are on your own to figure out how to make projects for it, MonoGame doesn't provide directions. Either case, MGCB will not work on Pi. Only game built for would work, not building games on it.

**Comment by mrhelmut** [comment]
Update on 3.8.1:

The release is mostly ready from a code perspective. We only have #7701 and #7197 to work on to consider 3.8.1 shippable.

We are however willing to wait for VS 2022 for Mac to fully release (which should be imminent) and for the documentation to be updated for 3.8.1 (I started working on it).

**Comment by mrhelmut** [comment]
As far as I can tell, 3.8.1 is ready.

There is still #7197 being investigated, but since it seems inconsistent, we might consider it for a later release/hotfix.

Should we wait for VS 2022 for Mac to reach GA?

**Comment by Lancelotbronner** [comment]
Personnaly, I don't think you should wait for VS2022 Mac, I'm currently using it and most issues I have with it are because MG 3.8.1 (and its updated dependencies) aren't the latest.

**Comment by FeodalherreN** [comment]
I agree with @Lancelotbronner,  I am super excited to try it out!

**Comment by mrhelmut** [comment]
@harry-cpp your call in regard waiting for VS for mac or not. Otherwise #7798 needs the extension to be hosted and linked before being merged, and then we're good to release 3.8.1 nugets and the windows extension.

**Comment by tomcashman** [comment]
Will there be a corresponding tag on the console repos?

**Comment by mrhelmut** [comment]
I will update the console repositories up to 3.8.1 and will check with Tom if we can tag them.

**Comment by aseprite-girl** [comment]
What are you waiting for? Christmas?!?

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-is-now-available/

**Comment by Lancelotbronner** [comment]
It has been a few days, is there something I could do to help with the release?

**Comment by mrhelmut** [comment]
Thanks for asking, there is nothing holding it back. We only need to do some maintenance on the build server and finding a time where all the admins are available (because we need to sync' when doing a release).

It should release anytime now, but since it is bound to our free time we can't announce a date in advance.

**Comment by aseprite-girl** [comment]
WOOHOOW!!! :-D

**Comment by mrhelmut** [comment]
The release process has been initiated: #7823

After PR has been merged, a few tasks will have to carried out:
- publishing the artifacts to nuget.org
- building the VS extensions and publishing them (the Windows extension will go the VS Marketplace, while the macOS extension will be self-hosted on monogame.net)
- updating #7798 to have the VS for mac extension link
- updating the master branch
- doing the actual release on github
- updating monogame.net download page to point to the documentation getting started, and explaining how to use the develop nuget feed
- announcing the release on the community site and pin it

**Comment by mrhelmut** [comment]
I will be looking into releasing 3.8.1 over the weekend.

**Comment by NickStrupat** [comment]
I love checking up on a future release many months later and finding out that it's about to be released!

**Comment by damian-666** [comment]
I'll  update right away but its the android/xamarin replacement im most intested in since netcore 6 is giving me everying i need now for PCs and im aimed at Steam now.   So im most curious about what happens next.   everynthign ur core team done seems amazing and the code flux on this vault has been mindblowing!!   i havent tried consoles at all though.   im not an engine developer im application level so i just have opionions about that stuff.

on a general topic..   I'm invited to a " coffee chat"  about tooling wiht Microsoft next week.. righ now all i want is drag and drop with surface pen to work like it does in notepad.   one bug fix.   so i can debug and tweak code, without the keyboard.  i dont wanan go back to command line tools and i dont really like this trend so i use the vs 2022 IDE and ill be focused on talkng about that.  

  if anyone has a bigger request  or different about their toolchain for developers that inhibits MG develepment... ill pitch it to them.. im using vs 2022 preview and they just added code search , indexed, to code and  options like  specific debug settings, i love this, because i hate big menus and dialogs  but dont want to use 1985 style terminals or shells.....

 pretty  they much already fixed all my complaints i was going to bitch about with their last update.  and my feature requests..  and  i think they are going the right direction after 20 years of .net ups and downs ..

But  if u guys need anything from them ill ask them directy.. monogame is the best use of Netcore that exists IMO. 

 im not sure about maui but im exited about using an ARM surface to make android apps via monogame.  i make my own ui for now because i dont trust new UI tech from them. Maui ? i donno if ill use that and get burned for it.   but i use WPF still for my level editor, with a MG window in it.  and its compiles under netcore now.  
 
 but ill use windows to develop, vs 2022  preview and decided a Surface fits my needs because mac doesnt have touch screens.  so itlll tell them to fix the start menu to  be more  like the new Search in visual studio.. Ill say Contana should be the front of the search,  and be able to parse natural language wthoujt Binging stuff stupidly..  thats what i want from them,  better AI  integrated to the  PC and to the apps as a way to discover and even set values of  settings and navigate without menus or consoles.  like i want to  say "show exceptions," turn on all CLR exceptions" an i want vs studio to do just that not bing it and tell me how to do it myslef.

**Comment by mrhelmut** [comment]
3.8.1 has been "soft launched".

We still have an ongoing issue: the MGCB editor for Windows can't be uploaded to nuget.org for some reason.

Once we figured it out, we'll post the announcement and change notes.

The documentation isn't online yet as well. Hoping to have everything up and running later today (or possibly tomorrow).

**Comment by SaySayTakamura** [comment]
> 3.8.1 has been "soft launched".
> 
> We still have an ongoing issue: the MGCB editor for Windows can't be uploaded to nuget.org for some reason.
> 
> Once we figured it out, we'll post the announcement and change notes.
> 
> The documentation isn't online yet as well. Hoping to have everything up and running later today (or possibly tomorrow).

Hello Mr.Helmut, sorry for the bothering, but installing the MGCB-EDITOR through the Nuget Package Manager (again, VS2022-Latest) since my start in MonoGame (some days ago) it's not operable giving the message:

"The package "dotnet-mgcb-editor" is marked as type dotnet-tool which is not suported by (Here goes project name)"

But gladly i did the instalation through the CLI and have been using it since then, and since the `--register` has been removed, i could not install the new version, from both Nuget and CLI.

The templates tho, works like a charm, updated the CLI ones and Downloaded the VS Extension.

Sorry for bothering once again and Congratulations in releasing this version of MonoGame.

**Comment by mrhelmut** [comment]
Hold on your horse, like noted the 3.8.1 documentation isn't online yet and this is a pre-release for now. Please don't expect replacing numbers to just work.

The MGCB Editor doesn't have to be installed or registered anymore. Please migrate your project to 3.8.1 using the 3.8.1 templates and not just by replacing the nuget reference. More specifically, you will need a ```.config/dotnet-tools.json``` file ([like defined in the new templates]([dotnet-tools.json](https://github.com/MonoGame/MonoGame/blob/develop/Templates/MonoGame.Templates.CSharp/content/MonoGame.Application.Android.CSharp/.config/dotnet-tools.json)) to tell .NET to install MGCB Editor. Then you'll be able to launch it from the CLI, or more conveniently just use the Visual Studio extension and you will be able to just double-click on the .mgcb file from the VS solution explorer.

**Comment by SaySayTakamura** [comment]
> Hold on your horse, like noted the 3.8.1 documentation isn't online yet and this is a pre-release for now. Please don't expect replacing numbers to just work.
> 
> I also noted that the MGCB Editor for 3.8.1 isn't online yet.
> 
> The MGCB Editor doesn't have to be installed or registered anymore. Please migrate your project to 3.8.1 using the 3.8.1 templates and not just by replacing the nuget reference. More specifically, you will need a ```.config/dotnet-tools.json``` file ([like defined in the new templates]([dotnet-tools.json](https://github.com/MonoGame/MonoGame/blob/develop/Templates/MonoGame.Templates.CSharp/content/MonoGame.Application.Android.CSharp/.config/dotnet-tools.json)) to tell .NET to install MGCB Editor. Then you'll be able to launch it from the CLI, or more conveniently just use the Visual Studio extension and you will be able to just double-click on the .mgcb file from the VS solution explorer.

Exactly, i created a project from the templates, still the same issue.

This is why i commented, and downgraded so i can work while the issue is dealt with.

I will migrate it back and leave for today, my back is killing me.

Have a great day and good luck.

**Comment by mrhelmut** [comment]
3.8.1 documentation is online. As soon as the MGCB Editor is on nuget.org, we'll be good to announce the release.

**Comment by BinarySpike** [comment]
This is blocking windows builds of the `mgdesktopgl` per the documentation https://docs.monogame.net/articles/getting_started/2_creating_a_new_project_netcore.html

🤷‍♂️

**Comment by mrhelmut** [comment]
[3.8.1 is now officially released](https://community.monogame.net/t/monogame-3-8-1/17786).
